#!/bin/bash
echo "=== 恩奇上下文清理工具 ==="
echo "當前問題：100% context used 66.1k/64k"
echo ""
echo "解決方案："
echo "1. 關閉當前對話視窗"
echo "2. 等待 30 秒"
echo "3. 重新開啟對話視窗"
echo ""
echo "預防措施："
echo "- 定期清理對話歷史"
echo "- 避免在單一對話中處理過多檔案"
echo "- 將複雜任務拆分為多個對話"
echo ""
echo "進階配置（需要重啟容器）："
echo "修改 ~/.openclaw/.env 添加："
echo "OPENCLAW_CONTEXT_WINDOW=128000"
echo ""
echo "然後執行："
echo "cd ~/openclaw && docker compose restart"
